### ISSUE TITLE
bug i map_to_objects ved bestemte 'navn' queries

### ISSUE THREAD

**Issue by websorz** [cvr-dev/cvr.dev-python#1]
Hvis man kalder cvr.virksomheder(navn='aldi') thrower den en exception ''list' object has no attribute 'get''

**Comment by micvbang** [comment]
Thanks for raising this issue! I'm able to recreate the issue and am looking at a fix :)

**Comment by micvbang** [comment]
You should be able to grab v0.2.1 now :)
